[package]
name = "lucerna"
version = "0.4.2"
authors = ["Kyando_2 <amehikoji@gmail.com>"]
edition = "2018"


[dependencies.liber]
git = "https://github.com/Lucerna-Lang/Liber"

[dependencies.structures]
git = "https://github.com/Lucerna-Lang/Structures"