[package]
name = "lucerna"
version = "0.6.2"
authors = ["Kyando_2 <amehikoji@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies.liber]
path = "../Liber"

[dependencies.structures]
path = "../Structures"

[dependencies.web]
path = "../Web"

[build-dependencies]
winres = "0.1"